### ISSUE TITLE
Remote Responses

### ISSUE THREAD

**Issue by wenig** [wenig/actix-telepathy#2]
- working with the `.send().into_actor()` interface

**Comment by Studiedlist** [comment]
I've made some progress with remote responses (will show later, it needs some refactoring :no_mouth:), but now I can't figure out how to test this case. 
I've tried to launch two clusters the way it done in other tests:
```rust
#[test]
fn test_send_with_response() {
    let _ = env_logger::builder().is_test(true).try_init();
    let ip1: SocketAddr = format!("127.0.0.1:{}", request_open_port().unwrap_or(8000))
        .parse()
        .unwrap();
    let ip2: SocketAddr = format!("127.0.0.1:{}", request_open_port().unwrap_or(8000))
        .parse()
        .unwrap();
    let arr = [
        (ip1, vec![]),
        (ip2, vec![ip1]),
    ];
    arr.par_iter()
        .enumerate()
        .for_each(|(i, (ip, vec))| match i {
            0 => test_start_actor(*ip, vec.clone()),
            1 => test_send_trigger(*ip, vec.clone()),
            _ => (),
        });
    panic!();
}

#[actix_rt::main]
async fn test_send_trigger(addr: SocketAddr, seeds: Vec<SocketAddr>) {
    let cluster = Cluster::new(addr, seeds);
    let actor = SendTestActor::new(cluster).start();
    sleep(Duration::from_millis(300)).await;
    actor.send(InternalTrigger()).await.unwrap();
}

#[actix_rt::main]
async fn test_start_actor(addr: SocketAddr, seeds: Vec<SocketAddr>) {
    let cluster = Cluster::new(addr, seeds);
    sleep(Duration::from_millis(200)).await;
    let actor = SendTestActor::new(cluster).start();
    sleep(Duration::from_millis(700)).await;
}
```
But when `SendTestActor` tries to send remote message (`remote_addr.do_send(ResponseTestMessage{});`), it panics with `NetworkInterface does not interact as RemoteActor` error

Full code of this test: https://pastebin.com/jp2zkpZJ

Do you have any ideas?

**Comment by Studiedlist** [comment]
It would be nice if you share or point to minimal working test with two actors communicating within one test. 

I managed to implement working request-response communication via oneshot channels in my project, but it is more high-level because it works on top of actix-telepathy, and it is not as efficient and elegant as it could be

**Comment by wenig** [comment]
Hi @Studiedlist,

Thanks for your effort, really appreciate it! I see. Your ClusterListener collects all new members and generates a `RemoteAddr` for each cluster member. These `RemoteAddr`s point to a `NetworkInterface` and also include a `AddrRepresentation` (https://github.com/wenig/actix-telepathy/blob/main/src/remote/addr/mod.rs#L24). The `AddrRepresentation` tells the receiver which exact Actor should receive this message. When collecting the `RemoteAddr`, they don't point to another `Actor` but rather to the receiving `NetworkInterface`. Therefore, you must define, which `Actor` on the receiving end shall finally receive the message. The `change_id` method (https://github.com/wenig/actix-telepathy/blob/main/src/remote/addr/mod.rs#L71) can help you here. The IDs are used when registering an `Actor` as a `RemoteActor` (https://github.com/wenig/actix-telepathy/blob/main/src/remote/actor.rs#L12). Every `Actor` should have an `::ACTOR_ID` attribute, which is simply its struct name (https://github.com/wenig/actix-telepathy/blob/main/actix-telepathy-derive/src/remote_actor.rs#L53). You could try to do the following before line 48 in your full test:

```rust
let mut remote_addr_test = remote_addr.clone();
remote_addr_test.change_id(SendTestActor::ACTOR_ID.to_string());
println!("{:?}", 
    remote_addr_test.send::<_, ResponseTest, _>(ResponseTestMessage{}, &self_addr.clone())
        .await
        .unwrap()
);
```

This address messing around is a bit inconvenient. If you have ideas for better structures, feel free to propose them ;)

Cheers

**Comment by wenig** [comment]
This example does something similar: https://github.com/wenig/telepathy-examples/blob/main/paper-example/src/example.rs

**Comment by Studiedlist** [comment]
> Therefore, you must define, which `Actor` on the receiving end shall finally receive the message

Oh god, I always forget about it. I think `change_id` is definitely subject to change. I will think about how to change api or enforce id change at compile time later

**Comment by wenig** [comment]
Looking forward to your solution! :+1:

**Comment by Studiedlist** [comment]
Please take a look at https://github.com/wenig/actix-telepathy/pull/67

**Comment by Studiedlist** [comment]
What if we make responses automatic?
As I see, `RemoteMessage` always have `()` as result. It would be nice to make `actix_telepathy` automatically send resulting message to remote sender if it is `RemoteMessage`. We can also make `actix_telepathy` handle `Option` and `Either` as `actix_web` does with extractors.
As of implementation, I think we can create new trait like `HandlerWithResponse`, which will act like actix `Handler`, but will accept as `Result` type either `Option` or `Either` with `RemoteMessage`, or `RemoteMessage` itself

**Comment by wenig** [comment]
Hey, sorry for the late reply! It would make the whole Response topic easier, that's true. However, I am afraid, sending empty remote messages is too much unnecessary network traffic. 

What do you think about an additional macro to define which remote messages can be received?

**Comment by Studiedlist** [comment]
Don't you think we can do something like:
```rust
trait HandlerWithResponse {
  type Response : MessageResponse;
}

trait MessageResponse: RemoteMessage;

impl<T> MessageResponse for T 
where T: RemoteMessage {}
```
This will not allow to send empty messages, but could be a bit inconvinient to refactor because if you need to change actor response from some message to `()`, you will need to change `HandlerWithResponse` trait to `Handler`

Another option is to allow any type as response (including () for no response), and send only actual messages without empty ones, but I can't exactly imagine how it could be implemented

As of macros, I think they will be a bit messy and could lead to more unexpected behavior or logic bugs

**Comment by wenig** [comment]
Can you draft a solution?

**Comment by Studiedlist** [comment]
I experimented with traits a bit, but it seems too hard to merge them into existing codebase. 
So I have other idea:
```rust
pub struct ResponseEnvelope(());

impl ResponseEnvelope {
    pub fn handle<F, M>(addr: RemoteAddr, f: F) -> ResponseEnvelope
    where
        F: Fn() -> M,
        M: RemoteMessage<Result = ResponseEnvelope>,
    {
        let message = f();
        addr.send(message);
        ResponseEnvelope(())
    }
}
```
We could mark `RemoteMessage` that will return some remote response by setting their `Message::Result` to `ResponseEnvelope`. `ResponseEnvelope` contains no information, but forces to use `ResponseEnvelope::handle`, because it is the only way to obtain it's instance, which is in turn required to implement `Handler`

## Example usage

We create `RemoteMessage` and mark it:
```rust
#[derive(RemoteMessage)]
#[with_response]
pub struct TestMessage;

#[derive(RemoteMessage)]
pub struct TestResponse(String);
```
`TestMessage` implements `Message<Result = ResponseEnvelope>` now.
Then we implement `Handler` for actor:
```rust
impl Handler<TestMessage> for TestActor {
  type Result = ResponseEnvelope;
  
  fn handle(&mut self, msg: TestMessage, _: &mut Self::Context) -> Self::Result {
    ResponseEnvelope::handle(self.response_addr, || {
      // Some message handling here
      TestResponse("Hello from the other side".to_string())
    })
  }
}
```

And so we have guarantee that `TestActor` will send some  `RemoteMessage` as a result of handling `TestMessage`

I am not sure that it will even compile for now, so I will refine and post updated version later (plus there might be more features like accepting `Either` as I mentioned above).
I hope you got the idea  

P.S. Naming is subject to change, looking forward for your variants of more suitable names

**Comment by Studiedlist** [comment]
Take a look at https://github.com/wenig/actix-telepathy/commit/28f8a0fdd85e03842ac30d2020848689b68caa91
It compiles, but I am not sure how to implement `MessageResponse` for now, will research it later

**Comment by callmeahab** [comment]
Any news on this. I'm looking for a solution that will allow me to send responses back from actors, and would be willing to research this further.

**Comment by Studiedlist** [comment]
I have implemented request-response model with `actix-telepathy`. 
See:
- https://gitlab.com/studiedlist/e-shop/-/blob/master/remote/src/product.rs  
- https://gitlab.com/studiedlist/e-shop/-/blob/master/http/src/product/service.rs  
- https://gitlab.com/studiedlist/e-shop/-/blob/master/web/src/product/service.rs

Implementation is (a little) complex and messy, but principle is the following:
1. `RemoteRequestService` of `system 1` receives internal message (say `InternalGetProductMessage`). These messages are sent from internal actors, which don't know anything about `actix-telepathy`
1. `RemoteRequestService` converts internal message into external `actix-telepathy` message (`InternalGetProductMessage` -> `ExternalGetProductMessage`) and sends it
1. Internal actor of `system 2` catches external message, computes (in our example, task is to find a product by id) and  broadcasts result locally as `InternalGetProductResponse`
1. `InternalGetProductResponse` is catched by `RemoteRequestService` of `system 2` and sent back to `system 1`

It would be great to create ubiquitous abstractions and make solution not as bloated and complex. If you up to, we could create separate crate, and after we test it out and stabilize a bit, offer changes to `actix-telepathy`

**Comment by wenig** [comment]
I will add an example as a work-around in the https://github.com/wenig/telepathy-examples repo. So far, we haven't found a good solution for remote responses.

**Comment by lucasmsoares96** [comment]
That would help a lot. Thanks.

**Comment by wenig** [comment]
I would like to move this to the discussion space: https://github.com/wenig/actix-telepathy/discussions/82
