### ISSUE TITLE
RemoteActor should use `match` instead of chaining `if`-`else`s

### ISSUE THREAD

**Issue by idanarye** [wenig/actix-telepathy#63]
I stumbled upon this project, and something caught my eye: https://github.com/wenig/actix-telepathy/blob/a236ebe7b67ed6acd443371b4c33af6762cc4f27/actix-telepathy-derive/src/remote_actor.rs#L26-L45

It seems you are composing a big `if`-`else` chain for checking the macro. Judging from [the macro expansion example docs](https://docs.rs/actix-telepathy/0.5.2/actix_telepathy/derive.RemoteActor.html#background), this looks like a remnant from an older iteration where you'd use a function to determine the concrete type of the remote message. But now that you are comparing `msg.identifier` - which is a `String` - wouldn't it be more efficient to use a `match` instead?

**Comment by wenig** [comment]
Hi, thank you for this comment! I'll have a look into this!

**Comment by wenig** [comment]
This will be added to the new release.
