### ISSUE TITLE
RemoteAddr change_id refactoring

### ISSUE THREAD

**Issue by Studiedlist** [wenig/actix-telepathy#68]
`change_id` is necessary to call in most cases, but it is easy to overlook due to lack of checks and warnings, plus can be confusing to debug, because error messages are not as helpful as they could

I propose introducing new struct, which represents "uninitialized" `RemoteAddr` without id. It is not usable before id change, so you can't miss calling `change_id`

The way I see it is something like:
```rust
#[derive(Deserialize, Serialize, Debug, Clone)]
pub struct RawRemoteAddr {
    pub socket_addr: SocketAddr,
    #[serde(skip_serializing)]
    #[serde(skip_deserializing)]
    pub network_interface: Option<Addr<NetworkInterface>>,
}

impl RawRemoteAddr {
    pub fn new(
        socket_addr: SocketAddr,
        network_interface: Option<Addr<NetworkInterface>>
    ) -> Self {
        Self {
            socket_addr,
            network_interface,
        }
    }

    pub fn into_addr(self) -> RemoteAddr {
        let RawRemoteAddr { socket_addr, network_interface } = self;
        RemoteAddr {
            socket_addr,
            network_interface,
            id: AddrRepresentation::NetworkInterface,
        }
    }

    pub fn change_id(self, id: String) -> RemoteAddr {
        let RawRemoteAddr { socket_addr, network_interface } = self;
        RemoteAddr {
            socket_addr,
            network_interface,
            id: AddrRepresentation::Key(id),
        }
    }

}
```

I've tried this, and it seems like it will not cause much effort to migrate for existing projects

**Comment by wenig** [comment]
Great! I'd do some renaming though. The `RawRemoteAddr` is not really an `Addr`. I tried to be as close as possible to the Actix concepts. What do you think about just `Node` or `ClusterNode`? And then for the implementation. I would suggest something like:

```rust
#[derive(Deserialize, Serialize, Debug, Clone)]
pub struct Node {  // or ClusterNode?
    pub socket_addr: SocketAddr,
    #[serde(skip_serializing)]
    #[serde(skip_deserializing)]
    pub network_interface: Option<Addr<NetworkInterface>>,
}

impl Node {
    pub fn new(
        socket_addr: SocketAddr,
        network_interface: Option<Addr<NetworkInterface>>
    ) -> Self {
        Self {
            socket_addr,
            network_interface,
        }
    }

    pub fn into_addr(self) -> RemoteAddr {  // Maybe then we don't need this method
        RemoteAddr {
            node: self,
            id: AddrRepresentation::NetworkInterface,
        }
    }

    pub fn get_remote_addr(&self, id: String) -> RemoteAddr {
        RemoteAddr {
            node: self.clone(),
            id: AddrRepresentation::Key(id),
        }
    }

}
```

... `RemoteAddr` could hold a `Node` object then. I think this would simplify the whole thing.

**Comment by Studiedlist** [comment]
I think you are right. Initially I thought of introducing as little breaking changes as possible, not of refactoring conception. 
`into_addr` could be omitted, but we should have some convinient way of creating `RemoteAddr` with `NetworkInterface` id instead
