### ISSUE TITLE
Tracing

### ISSUE THREAD

**Issue by Studiedlist** [wenig/actix-telepathy#71]
It would be handy to have built-in automatic tracing. We could have simply inserted `log::trace` somewhere in wrappers-handlers, but I think there should be configuration of some kind.
We could add something like `type Tracing` in `RemoteActor` and `RemoteMessage` traits to have ability to trace individual actors or messages. 

My view is the following:
- When tracing on actor is on, all messages with enabled tracing are traced. When tracing on actor is off, no messages are traced.
- Tracing is off by default for actor, and on by default for message. 
- Tracing can be selected with macro arguments like `#[derive(RemoteActor[tracing = false])]`

Another option I see is to set tracing for individual actors and messages with environment variables, but I can't imagine convenient way to do this.

**Comment by wenig** [comment]
Is there something similar for the Actix lib? Maybe that would work here right away?

**Comment by Studiedlist** [comment]
I enabled tracing on my project and didn't see anything like that. Most likely it is not an issue in Actix lib because there are fewer possibilities for message not to arrive or to arrive not correctly

I also read about tracing log level a bit, and it seems like this log level is not exactly what I meant to use. My idea is to log what messages actors sent and received. Maybe it will be best fitted on debug level

**Comment by wenig** [comment]
No progress here. Please open another issue if you have a solution for tracing.
