### ISSUE TITLE
Main thread panicking when remote actor id is not found.

### ISSUE THREAD

**Issue by lucasmsoares96** [wenig/actix-telepathy#85]
My application environment is composed of 3 processes with their respective actors: 1 manager and 2 workers. First the Manager starts and waits for the first Worker to join the cluster.

```rust
fn handle(&mut self, msg: ClusterLog, _ctx: &mut Self::Context) -> Self::Result {
         match msg {
             ClusterLog::NewMember(node) => {
                 println!("New member joined the cluster.");
                 let remote_addr = node.get_remote_addr("Worker".to_string());
                 println!("{:?}", node.socket_addr);
                 remote_addr.do_send(Register {
                     source: self.own_addr.clone(),
                 })
             }
             ClusterLog::MemberLeft(_ip_addr) => {
                 println!("Member left the cluster.")
             }
         }
     }
```
Then the first woker comes in and everything works fine

```rust
fn handle(&mut self, msg: ClusterLog, _ctx: &mut Self::Context) -> Self::Result {
         match msg {
             ClusterLog::NewMember(node) => {
                 println!("New member joined the cluster.");
                 let remote_addr = node.get_remote_addr("Manager".to_string());
                 println!("{:?}", node.socket_addr);
                 remote_addr.do_send(Register {
                     source: self.own_addr.clone(),
                 })
             }
             ClusterLog::MemberLeft(_ip_addr) => {
                 println!("Member left the cluster.")
             }
         }
     }
```

When the second Worker joins the cluster, it looks for the Manager on the 2 other nodes. One is the Manager in fact, but the other is a Worker and does not have the Manager actor. As a result, the main thread panics. The same happens with the other 2 processes.

I think a better approach would be to return an `Option<RemoteAddr>` on the `node.get_remote_addr` line.

**Comment by wenig** [comment]
The creation of the `RemoteAddr`,  when calling `node.get_remote_addr`, does not have information about existing actors on other nodes. This has 2 reasons: **1.** We want the user to take care of this logic. **2.** (and even more important) The way to find out that a `Manager` actor exists on the other node is asking and receiving a message. That's unnecessary communication over the network that can be avoided with a different program logic. Your Worker actor could for example have an attribute that informs which `socket_addr` is a worker and which is a manager.

**Comment by lucasmsoares96** [comment]
I think that identifying by `socket_addr` is not a good solution, given that the number of workers must increase with the need and in a containerized environment the IPs are not known in advance. I think I'll need to create a ClusterListener actor with an `is_manager` attribute, which I don't think is the most elegant solution.

**Comment by wenig** [comment]
That should work, correct! Another possibility would be to turn off the panicking and turn it into a warning, and the sent message with the non-existent recipient would be ignored.

**Comment by lucasmsoares96** [comment]
This seems like a better alternative to me. The code would be more readable and organized.

**Comment by wenig** [comment]
I'll add it to the new release 0.6.0.
